### ISSUE TITLE
npm scripts lose run permissions.

### ISSUE THREAD

**Issue by sterpe** [node-freight/freight#22]
Packages that have npm run scripts such as `postinstall` fail to unbundle correctly in the npm install step  from freight server presumably b/c (in the process of creating the freight server's tar.gz) the permissions are converted from 755 to 644 (read only).

**Comment by sterpe** [comment]
e.g., a package like this https://www.npmjs.com/package/jest-babel-preprocessor

**Comment by vladikoff** [comment]
I see, I think we should be able to fix the permissions, I noticed there is also a postinstall script that modifies the package.json on the fly or something https://github.com/sterpe/jest-babel-preprocessor/blob/master/scripts/postinstall

**Comment by sterpe** [comment]
Yes.  Tho, even when I d/l the tar.gz from my freight-server and unpack I see that the file permissions for executables are changed.

I can put in a PR for this if you want.

**Comment by sterpe** [comment]
Re package.json mod: it only adds a custom field if it doesnt already exist, mostly to save me a bunch of repetitive typing.

**Comment by vladikoff** [comment]
> I can put in a PR for this if you want.

@sterpe that would be useful, if you have time. I can add tests to it myself, you can just fix up the code if you want.
