### ISSUE TITLE
freight dependency resolution misses indirect dependencies

### ISSUE THREAD

**Issue by madmuffin1** [node-freight/freight#27]
We really love the idea and the concept of freight, setup a freight server to speed up our build process.

Unfortunately, we ran into a issue, where a indirect dependency is not part of the freight bundle, whereas a local install works fine.

I set up a minimal example (https://github.com/madmuffin1/freight-issue) with all output and steps to reproduce, for convenience duplicated here:

> ## Steps to reproduce:
> 1. checkout project, run `npm install` and verify that `gulp test` works
> 2. create freight bundle using `freight create`, wait for freight-server to be ready
> 3. checkout project (in a fresh location)
> 4. run `freight` to retrieve dependencies bundle
> 5. now one would expect `gulp test` to run successfully, but it fails (producing error [error.log](https://github.com/madmuffin1/freight-issue/blob/master/error.log))

Error message (without stacktrace, see linked error.log above for full trace):

> `Error: Cannot find module 'bplist-parser'`
## Versions in our setup:
- Tried build clients with node 5.6, 5.5, 5.4 and 4.2 (all of them work when installing `npm install`, none of them work using freight) 
- Freight server running on node 5.5, npm 3.3.12

**Comment by madmuffin1** [comment]
The problem apparently only happens on linux.

**Comment by sterpe** [comment]
Only with that module cordova?

**Comment by vladikoff** [comment]
I don't see anything too special about that project at first glance. MAYBE it has to do with bundleDependencies, will check it out. Thanks for the issue!

**Comment by madmuffin1** [comment]
we stopped using this stack, I will close this issue so it gets of my issue list.
