### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by juliendangers** [node-freight/freight#31]
> If your Freight Server is down or the bundle is missing, then Freight will still exit with status code 0. This way the build won't fail and the CI will fallback to NPM or Bower registries.

If freight-server is down, or URL is wrong, exit code will be 1

To reproduce, execute following bash code into a directory with a package.json

```
#!/bin/bash

export FREIGHT_URL=http://example.com
export FREIGHT_PASSWORD=your_password
freight create
echo $?
```

EDIT : my mistake, exit code 0 is only for `freight`

Nevertheless, I want to create a bundle at the last step of my CI (aka if tests succeeded, I can create a bundle), but build fails if `freight create` fails. 

@vladikoff What would think of an option to never exit with code 1 ?

**Comment by vladikoff** [comment]
@juliendangers hey, we had that before but changed the behaviour to act more like any other unix program (aka "If something goes wrong exit with status code" > 0) 

See here: https://github.com/node-freight/freight/pull/12 
From the pull about you can just do something like: `freight create || echo "Server Down"`

**Comment by juliendangers** [comment]
Ok, I understand
I had `exit 0` to bash script, thx
