### ISSUE TITLE
NPM rebuild throws error spawning process on Windows

### ISSUE THREAD

**Issue by tony99nyr** [node-freight/freight#32]
After a freight get, it extracts, then spawns a process to run `npm rebuild`
    `var npmRebuild = spawn('npm', ['rebuild'], { cwd: process.cwd() });`

This line doesn't work on Windows.  I'm on Windows 7, node v4.4.5.

![image](https://cloud.githubusercontent.com/assets/1902199/17036526/a34b5dfe-4f5a-11e6-9bdf-5d101a12257e.png)

**Comment by vladikoff** [comment]
@tony99nyr try using latest `master`, see fix in https://github.com/node-freight/freight/commit/de2d91a5d236027a7a348ead34b3579a6d9d7f19

**Comment by tony99nyr** [comment]
Ah. Awesome!  Do you mind running `npm version patch && npm publish` ?

**Comment by tony99nyr** [comment]
Looks like you already created 0.5.3 actually. Simply `npm publish` and I will close this issue.

**Comment by vladikoff** [comment]
@tony99nyr to avoid breaking builds I published it as 0.6.0. Enjoy!

**Comment by tony99nyr** [comment]
Awesome! Thanks very much!!
